### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by JiajianLu** [MarlonCajamarca/Keras-LSTM-Trajectory-Prediction#1]
Hi, can you also upload the link to download your training and testing data? Thank you!

**Comment by MarlonCajamarca** [comment]
Hi @JiajianLu 
Of course! You can download a raw dataset [here](https://drive.google.com/open?id=19vXL8NgqXnVdelKTJUa6mKd5fTbCv5Kg). Once you download the `raw_dataset`, you can create a ready-to-use training/test `train_test.hdf5` dataset by using `opt_train_test_dataset_transformer.py` **or** `train_test_dataset_transformer.py` scripts, like this:

```javascript
python3 train_test_dataset_transformer.py /Path/to/input_raw_dataset.hdf5 /Path/to/output/dataset/folder/<output_train_dataset.hdf5> config_transformer.json
```

Then, you could use the different training and inference scripts (`train.py`, `train_DrBN.py`) to play around with different model configurations and hyperparameters. Please check the `ReadMe.md` file for detailed documentation about the different tools and corresponding Command-Line-Interface examples executions. 
Have fun!

**Comment by JiajianLu** [comment]
Thank you @MarlonCajamarca! Does the dataset include type of objects (e.g. pedestrian, car, bicycle) and do you consider it as one of the inputs to the network?

**Comment by MarlonCajamarca** [comment]
Hi @JiajianLu 

Sorry for the late response. This is the workflow now: We use the `raw_dataset_creator` tool for generating a `raw_dataset.h5` file containing all the sample sequences, it does not matter the `trajectory_length` or the type of vehicle performing that trajectory. However, in this `raw_dataset.h5` each of the appended dataset/trajectory sample has its own attribute which captures the type of vehicle performing that sample trajectory (see [this link](http://docs.h5py.org/en/stable/high/attr.html) for more info) for further filtering processes.

Then, we used one of the `train_test_transformator` tools for creating the final train/test datasets where we filter each of the input trajectories and keep only the trajectories associated with a specific or group of specific vehicle classes using the `classes_2_extract` hyperparameter available in the  `config_transform.json` file. 

For example, classes that have been used for creating the datasets are: `classes_2_extract = ["LIGHTWEIGHT_AUTOMOTIVE_VEHICLE", "BUS", "VAN"]`

We can also create a trajectory predictor for PEDESTRIANS, MOTORCYCLES, and so on. However, the actual datasets do not comprise these additional classes yet. I will be adding various datasets composed by other classes apart from these first baseline categories, so keep in touch for the incoming updates. 

Regards, Marlon!
